import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";
import type { Session } from "next-auth"; // Importe o tipo Session

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageProps: { session },
}: Readonly<{
  children: React.ReactNode;
  pageProps: { session?: Session | null };
}>) {
  console.log("Session in RootLayout:", session); // Adicione este log
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session} refetchInterval={5 * 60}>
        <ToastContainer />

        {children}
        </SessionProvider>
      </body>
    </html>
  );
}